---
name: lint

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: "0 13 * * *"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [29, master]
    steps:
      - uses: actions/checkout@v2
      - name: Build test container
        run: docker build --build-arg EMACS_VERSION=${{ matrix.emacs_version }} --tag projection-test .
      - name: Run linters
        run: docker run --rm --volume .:/workarea --workdir /workarea projection-test sh -c 'cask install && make lint'
