---
name: test

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: "0 13 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [28, master]
    steps:
      - uses: actions/checkout@v2
      - name: Build test container
        run: docker-compose build --build-arg EMACS_VERSION=${{ matrix.emacs_version }}
      - name: Run tests
        run: docker-compose run --rm dev sh -c 'cask install && make test'
